export type {
	AnthropicMessagesCompat,
	Api,
	AssistantImages,
	AssistantMessage,
	AssistantMessageDiagnostic,
	AssistantMessageEvent,
	CacheRetention,
	Context,
	DiagnosticErrorInfo,
	ImageContent,
	ImagesApi,
	ImagesContext,
	ImagesInputContent,
	ImagesModel,
	ImagesOptions,
	ImagesOutputContent,
	ImagesProvider,
	ImagesStopReason,
	KnownApi,
	KnownImagesApi,
	KnownImagesProvider,
	KnownProvider,
	Message,
	Model,
	ModelThinkingLevel,
	OpenAICompletionsCompat,
	OpenAIResponsesCompat,
	OpenRouterRouting,
	Provider,
	ProviderImagesOptions,
	ProviderResponse,
	ProviderStreamOptions,
	SimpleStreamOptions,
	StopReason,
	StreamOptions,
	TextContent,
	TextSignatureV1,
	ThinkingBudgets,
	ThinkingContent,
	ThinkingLevel,
	ThinkingLevelMap,
	Tool,
	ToolCall,
	ToolResultMessage,
	Transport,
	Usage,
	UserMessage,
	VercelGatewayRouting,
} from "@earendil-works/rozsa-model-types";

export type { AssistantMessageEventStream } from "./utils/event-stream.ts";

import type {
	Api,
	AssistantImages,
	Context,
	ImagesApi,
	ImagesContext,
	ImagesModel,
	ImagesOptions,
	Model,
	StreamOptions,
} from "@earendil-works/rozsa-model-types";
import type { AssistantMessageEventStream } from "./utils/event-stream.ts";

export type StreamFunction<TApi extends Api = Api, TOptions extends StreamOptions = StreamOptions> = (
	model: Model<TApi>,
	context: Context,
	options?: TOptions,
) => AssistantMessageEventStream;

export type ImagesFunction<TApi extends ImagesApi = ImagesApi, TOptions extends ImagesOptions = ImagesOptions> = (
	model: ImagesModel<TApi>,
	context: ImagesContext,
	options?: TOptions,
) => Promise<AssistantImages>;
