[package]
name = "rozsa-gui"
version.workspace = true
edition.workspace = true

[lib]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
rozsa-app = { path = "../rozsa-app" }
rozsa-core = { path = "../rozsa-core" }
rozsa-model = { path = "../rozsa-model" }
tracing = { workspace = true }
dashmap = { workspace = true }
uuid = { version = "1", features = ["v4"] }
dirs = "6"
